export const DELIVERYFEE = 6

export const HOME_VIEW_REQUEST = "HOME_VIEW_REQUEST"
export const HOME_VIEW_SUCCESS = "HOME_VIEW_SUCCESS"
export const HOME_VIEW_FAIL = "HOME_VIEW_FAIL"

export const PERSONALIZED_BAG_REQUEST = "PERSONALIZED_BAG_REQUEST"
export const PERSONALIZED_BAG_SUCCESS = "PERSONALIZED_BAG_SUCCESS"
export const PERSONALIZED_BAG_FAIL = "PERSONALIZED_BAG_FAIL"
export const PERSONALIZED_BAG_RESET = "PERSONALIZED_BAG_RESET"

export const BAG_DETAIL_REQUEST = "BAG_DETAIL_REQUEST"
export const BAG_DETAIL_SUCCESS = "BAG_DETAIL_SUCCESS"
export const BAG_DETAIL_FAIL = "BAG_DETAIL_FAIL"

export const ALL_BAGS_REQUEST = "ALL_BAGS_REQUEST"
export const ALL_BAGS_SUCCESS = "ALL_BAGS_SUCCESS"
export const ALL_BAGS_FAIL = "ALL_BAGS_FAIL"

export const NEW_BAGS_REQUEST = "NEW_BAGS_REQUEST"
export const NEW_BAGS_SUCCESS = "NEW_BAGS_SUCCESS"
export const NEW_BAGS_FAIL = "NEW_BAGS_FAIL"

export const FEATURED_BAGS_REQUEST = "FEATURED_BAGS_REQUEST"
export const FEATURED_BAGS_SUCCESS = "FEATURED_BAGS_SUCCESS"
export const FEATURED_BAGS_FAIL = "FEATURED_BAGS_FAIL"

export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_FAIL = "ADD_CART_FAIL"

export const ADJUST_HEIGHT_REQUEST = "ADJUST_HEIGHT_REQUEST"
export const ADJUST_HEIGHT_SUCCESS = "ADJUST_HEIGHT_SUCCESS"
export const ADJUST_HEIGHT_FAIL = "ADJUST_HEIGHT_FAIL"

export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST"
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS"
export const CHECKOUT_FAIL = "CHECKOUT_FAIL"

export const ADD_WISH_REQUEST = "ADD_WISH_REQUEST"
export const ADD_WISH_SUCCESS = "ADD_WISH_SUCCESS"
export const ADD_WISH_FAIL = "ADD_WISH_FAIL"





